[package]
name = "lumi-ai-desktop"
version = "0.1.0"
description = "Lumi-AI Desktop"
authors = ["Lumi-AI contributors"]
edition = "2021"

[lib]
name = "lumi_ai_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
